import '@/styles/reset.css';
import '@/styles/globals.css';
import { myFont } from '../../public/fonts/markpro';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={myFont.className}>
      <body>{children}</body>
    </html>
  );
}
